//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kellerhoff.Codigo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KellerhoffEntities : DbContext
    {
        public KellerhoffEntities()
            : base("name=KellerhoffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_HomeSlide> tbl_HomeSlide { get; set; }
        public virtual DbSet<tbl_Oferta_Rating> tbl_Oferta_Rating { get; set; }
        public virtual DbSet<tbl_Recall> tbl_Recall { get; set; }
    }
}
