//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kellerhoff.Codigo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Oferta_Rating
    {
        public int ofr_idOferta_Rating { get; set; }
        public Nullable<int> ofr_idOferta { get; set; }
        public System.DateTime ofr_fecha { get; set; }
        public Nullable<int> ofr_idCliente { get; set; }
        public Nullable<bool> ofr_isDesdeHome { get; set; }
    }
}
