//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kellerhoff.Codigo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Recall
    {
        public int rec_id { get; set; }
        public string rec_titulo { get; set; }
        public string rec_descripcion { get; set; }
        public string rec_descripcionReducido { get; set; }
        public string rec_descripcionHTML { get; set; }
        public Nullable<System.DateTime> rec_FechaNoticia { get; set; }
        public Nullable<System.DateTime> rec_FechaFinNoticia { get; set; }
        public Nullable<System.DateTime> rec_Fecha { get; set; }
        public Nullable<bool> rec_visible { get; set; }
    }
}
