//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kellerhoff.Codigo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HomeSlide
    {
        public int hsl_idHomeSlide { get; set; }
        public string hsl_titulo { get; set; }
        public string hsl_descr { get; set; }
        public string hsl_descrReducido { get; set; }
        public string hsl_descrHtml { get; set; }
        public string hsl_descrHtmlReducido { get; set; }
        public int hsl_tipo { get; set; }
        public Nullable<int> hsl_idRecursoDoc { get; set; }
        public string hsl_NombreRecursoDoc { get; set; }
        public Nullable<int> hsl_idRecursoImgPC { get; set; }
        public Nullable<int> hsl_idRecursoImgMobil { get; set; }
        public Nullable<int> hsl_idOferta { get; set; }
        public string hsl_etiqueta { get; set; }
        public bool hsl_publicar { get; set; }
        public bool hsl_activo { get; set; }
        public System.DateTime hsl_fecha { get; set; }
        public Nullable<int> hsl_orden { get; set; }
        public int hsl_RatingCount { get; set; }
    }
}
